### ISSUE TITLE
License

### ISSUE THREAD

**Issue by strugee** [jdherg/octopus-holdings#3]
This project doesn't have a license, but probably should. See https://choosealicense.com/

<3

**Comment by jdherg** [comment]
I agree! Thanks for filing! I need to figure out how to get it exempted from my employer's IP agreement and figure out in a less "hope for the best" way how to be more confident I'm respecting the licenses of the orgs the SVGs and emoji mappings came from.

**Comment by strugee** [comment]
:tada: thanks @jdherg!

**Comment by jdherg** [comment]
Added the MIT license.

(Incidentally, also shuffled third party code into a third party folder and copied appropriate licenses from those projects.)
